// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecfdypbqbmlizegmlhru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZmR5cGJxYm1saXplZ21saHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjI1NDEsImV4cCI6MjA3NTczODU0MX0.nzk8tAW3oifnde8iI0T6Anir1F2_soRYKJkUv7moIOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});